### ISSUE TITLE
using `graphql-codegen-factories/operations` fails on `this.schema.getRootType`

### ISSUE THREAD

**Issue by jsve** [zhouzi/graphql-codegen-factories#73] opened 2023-02-06 19:19 UTC
With plugins as:

```javascript
plugins: [
   'typescript',
   'typescript-operations',
   'typescript-urql',
   'graphql-codegen-factories/schema',
   'graphql-codegen-factories/operations',
],
```
I get this error message
[FAILED] this.schema.getRootType is not a function

**Comment by zhouzi** [comment] 2023-02-12 06:50
Could you share a reproduction please? Feel free to use the minimal example as a starting point: https://stackblitz.com/github/zhouzi/graphql-codegen-factories/tree/main/examples/minimal?file=package.json

It could come from a specificity in the schema, a graphql version, mixing some plugins together or anything. With a reproduction, it'll be much easier to track down what's going wrong 🙏

**Comment by zhouzi** [comment] 2023-02-27 16:59
@jsve are you still having issues using the plugin? It'd be really helpful if you could share a reproduction.

**Comment by zhouzi** [comment] 2023-03-25 06:37
I am closing this issue but feel free to reopen with more details.

**Closed by zhouzi** 2023-03-25 06:37 UTC

**Comment by alexsandiiarov** [comment] 2023-11-10 01:11
Same issue with the latest graphql codegen:
```json
"@graphql-codegen/cli": "5.0.0",
"@graphql-codegen/client-preset": "4.1.0",
 ```

**Comment by Cordazar** [comment] 2024-02-26 10:19
And still same: 

```json
        "@graphql-codegen/cli": "5.0.2",
        "@graphql-codegen/client-preset": "4.2.4",
```

Changing to these three instead of preset doesn't work either:

```json
        "@graphql-codegen/typescript": "4.0.6",
        "@graphql-codegen/typescript-operations": "4.2.0",
        "@graphql-codegen/typescript-react-apollo": "4.3.0",
```

Looks to me like the format of the schema in the file `graphql-codegen-factories/build/operations/FactoriesOperationsVisitor.js` is not `GraphQLSchema` or an extension of it.

**Comment by zhouzi** [comment] 2024-02-26 10:52
I'll update the versions and see if I can reproduce this bug.

**Comment by Cordazar** [comment] 2024-02-26 11:01
Running `console.log(Object.getOwnPropertyNames(this.schema.__proto__));` gives:

```js
[
  'constructor',
  'getQueryType',
  'getMutationType',
  'getSubscriptionType',
  'getTypeMap',
  'getType',
  'getPossibleTypes',
  'getImplementations',
  'isPossibleType',
  'isSubType',
  'getDirectives',
  'getDirective',
  'toConfig'
]
```

**Comment by zhouzi** [comment] 2024-02-26 13:39
Thanks for sharing! I suspect the issue is that the plugin doesn't use the same version of the packages as the project. But I will have to run some tests.

**Comment by zhouzi** [comment] 2024-03-03 09:21
@Cordazar could you share the parts of your package.json that are related to graphql/codegen, please?

**Comment by Cordazar** [comment] 2024-03-04 19:33
```js
    "@graphql-codegen/add": "5.0.2",
    "@graphql-codegen/cli": "5.0.2",
    "@graphql-codegen/client-preset": "4.2.4",
    "@graphql-codegen/typescript": "4.0.6",
    "@graphql-codegen/typescript-operations": "4.2.0",
    "@graphql-codegen/typescript-react-apollo": "4.3.0",
    "graphql-codegen-typescript-mock-data": "3.7.1",
```

I've tried it both with the `preset: 'client'` option and also manually by using the plugins directly:
```js
    'typescript',
    'typescript-operations',
    'typescript-react-apollo',
    'graphql-codegen-factories/schema',
    'graphql-codegen-factories/operations'
```

**Comment by prztrz** [comment] 2024-10-09 11:46
hello any news on this?

**Comment by zhouzi** [comment] 2024-10-10 05:02
I am afraid I have not found enough time to track down the issue. Any help is welcomed.
