### ISSUE TITLE
compatability with `add` plugin

### ISSUE THREAD

**Issue by jsve** [zhouzi/graphql-codegen-factories#72] opened 2023-02-06 15:18 UTC
When running the plugin with `typesPath` config, i.e. generating to a separate file than the types, and the `add` plugin (https://the-guild.dev/graphql/codegen/plugins/other/add) the added lines gets added after the `import` statement.

I get this:
``` javascript
import * as Types from 'libs/some-path-to-the-types-file';


/* eslint-disable no-prototype-builtins, @typescript-eslint/no-non-null-assertion */
// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
```

but would expect this:
``` javascript
/* eslint-disable no-prototype-builtins, @typescript-eslint/no-non-null-assertion */
// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
import * as Types from 'libs/some-path-to-the-types-file';
```

**Comment by zhouzi** [comment] 2023-02-06 17:55
What is adding the `eslint-disable` comments? It'd help a lot of you could share an example or your `codegen.yml` 🙏

**Comment by jsve** [comment] 2023-02-07 08:36
Sorry, i thought the link to the plugin was enough. The `add` plugin is meant to be used to add arbritary code into the generated files. The reason would be similar as in the issue message, like adding lint-ignores to keep linters happy.

The plugin section would be something like this:

```javascript
plugins: [
        {
          add: {
            content: `
              /* eslint-disable no-prototype-builtins, @typescript-eslint/no-non-null-assertion */
              // eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
            `
          },
        },
        'graphql-codegen-factories/operations',
      ]
```

**Comment by zhouzi** [comment] 2023-02-12 06:42
That's strange because the add plugin is known to work well with this plugin. It's used in the "usage with faker example": https://github.com/zhouzi/graphql-codegen-factories/tree/main/examples/usage-with-faker

I just tried to reproduce this issue with a simpler setup and everything is working as intended: https://stackblitz.com/edit/github-zkzrvh?file=generated/factories.ts

It would help a lot if you could share a reproduction starting from this Stackblitz 🙏

**Comment by zhouzi** [comment] 2023-02-27 16:59
@jsve are you still having issues using the `add` plugin with this one?

**Comment by zhouzi** [comment] 2023-03-25 06:39
I am closing this issue as the `add` plugin is supported by the library as shown in the examples. To be honest there's no relation between the plugins and they both operate in different spaces so I can't think of a reason why they would influence each other.

But feel free to reopen if you have more details.

**Closed by zhouzi** 2023-03-25 06:39 UTC
